# fly.toml file generated for late-rain-8720 on 2023-12-25T17:24:49+01:00

app = "late-rain-8720"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[services]]
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[mounts]]
  source = "activepieces_vol"
  destination = "/root/.activepieces"

